import React from "react";
import "./styles/Standard.css";
import AudioPlayer from "./AudioPlayer";
import Contact from "./Contact";
import CadmiumRedFLAC from "./images/cadmium red 2026-01-22 0851.flac";
// Fallback will be automatically generated by replacing .flac with .mp3 if needed
const CadmiumRedMP3 = "https://portfoliomusic.s3.us-east-1.amazonaws.com/cadmium+red+2026-01-22+0851.mp3";

const DJMixes = ({ setNextSection, activeSection }) => {
	return (
		<>
			<div className="music-container">
				<div className="back-arrow-container">
				</div>
				<div className="player">
					<AudioPlayer 
						src={CadmiumRedFLAC}
						fallbackSrc={CadmiumRedMP3}
						title="Verdigris"
						artist="ARIANA ROSEMAN"
					/>
				</div>
			</div>
			{/* <div className="special-bar-container">
				<div className="onerem-bar"></div>
			</div> */}
			{/* <div className="contact-parent">
				<Contact />
			</div> */}
		</>
	);
};

export default DJMixes;
